@url = localhost:8080/geoserver/rest
@username = admin
@password = geoserver
@workspace = legacy
@coveragestore = testcog
@coverage = testcog

###

// create a workspace

POST {{url}}/workspaces
Authorization: Basic {{username}}:{{password}}
content-type: application/json

{
  "workspace": {
    "name": "{{workspace}}"
  }
}

###

// create a new coverage store

# @prompt azureStorageAccountKey

POST {{url}}/workspaces/{{workspace}}/coveragestores
Authorization: Basic {{username}}:{{password}}
content-type: application/json

{
  "coverageStore": {
    "name": "{{coveragestore}}",
    "type": "GeoTIFF",
    "enabled": true,
    "workspace": {
      "name": "{{workspace}}",
    },
    "url": "cog://https://s32stg.blob.core.windows.net/bhp-legacy-data-spatial/testcog.tif",
    "connectionParameters": {
      "entry": [
        {
          "@key": "password",
          "$": "{{azureStorageAccountKey}}"
        },
        {
          "@key": "user",
          "$": "s32stg"
        }
      ]
    },
    "metadata": {
      "entry": {
        "@key": "CogSettings.Key",
        "cogSettings": {
          "useCachingStream": false,
          "rangeReaderSettings": "Azure"
        }
      }
    },
  }
}

###

// create a new coverage

POST {{url}}/workspaces/{{workspace}}/coveragestores/{{coveragestore}}/coverages
Authorization: Basic {{username}}:{{password}}
content-type: application/json

{
  "coverage": {
    "name": "{{coverage}}",
    "nativeName": "{{coverage}}"
  }
}
