version: 3

tasks:
  format:
    desc: Format the codebase
    cmds:
      - uv run black cog_converter/ tests/
      - uv run isort cog_converter/ tests/
  lint:
    desc: Lint the codebase
    cmd: uv run ruff check --fix cog_converter/ tests/

  convert:
    desc: Run the COG Converter over the test data
    cmd: uv run python -m cog_converter --config sample_config.json tests/data

  reconvertandupload:
    desc: Run the COG Converter over the test data don't skip and do upload
    cmd: uv run python -m cog_converter --config sample_config.json --enable-storage --no-skip-processed tests/data
