version: 3

tasks:
  format:
    desc: Format the codebase
    cmds:
      - uv run black cog_converter/
      - uv run isort cog_converter/
  lint:
    desc: Lint the codebase
    cmd: uv run ruff check --fix cog_converter/

  convert:
    desc: Run the COG Converter over the test data
    cmd: uv run python -m cog_converter test_data
